### ISSUE TITLE
Abstracting JSON

### ISSUE THREAD

**Issue by adamhathcock** [khellang/Nancy.Swagger#58]
I noticed you explicitly removed the usage of JSON.NET.  I'd like to add support back in via an interface.  Would this be useful?  Is there an interface that already exists?  I haven't stared too hard at the abstractions so I'm unsure if I just need to implement an already existing interface.

**Comment by khellang** [comment]
We take care of all serialization internally because the Swagger schema (the one consumed by swagger-ui) is strict about how things are serialized, so there should be no need to specify your own serializer IMO. You'd just risk breaking the schema. What's the reason you want to change the serializer?

**Comment by adamhathcock** [comment]
I think the specific issue is that Nullable values are serialized poorly.

I just thought having control would be useful but I understand about having strict serialization requirements

**Comment by khellang** [comment]
What do you mean by serialized poorly? We can certainly tweak SimpleJson if thats necessary.

**Comment by adamhathcock** [comment]
Here's a sample:

{
  "action_id": "Nullable`1",
  "created_by": "Nullable`1",
  "created_date": "",

Those Nullables are Nullable<Guid>
